#DAC section
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_clk}]
set_property SLEW SLOW [get_ports {dac_data[*]}]
set_property SLEW SLOW [get_ports {dac_clk}]
#set_property DRIVE 10 [get_ports {dac_data[*]}]
#set_property DRIVE 10 [get_ports {dac_clk}]

set_property IO_0_14 [get_ports {dac_data[0]}]
set_property IO_L1P_T0_D00_MOSI_14 [get_ports {dac_data[1]}]
set_property IO_L1N_T0_D01_DIN_14 [get_ports {dac_data[2]}]
set_property IO_L2P_T0_D02_14 [get_ports {dac_data[3]}]
set_property IO_L2N_T0_D03_14 [get_ports {dac_data[4]}]
set_property IO_L3P_T0_DQS_PUDC_B_14 [get_ports {dac_data[5]}]
set_property IO_L3N_T0_DQS_EMCCLK_14 [get_ports {dac_data[6]}]
set_property IO_L4P_T0_D04_14 [get_ports {dac_data[7]}]
set_property IO_L4N_T0_D05_14 [get_ports {dac_data[8]}]
set_property IO_L5P_T0_D06_14 [get_ports {dac_data[9]}]
set_property IO_L5N_T0_D07_14 [get_ports {dac_data[10]}]
set_property IO_L6P_T0_FCS_B_14 [get_ports {dac_data[11]}]
set_property IO_L6N_T0_D08_VREF_14 [get_ports {dac_data[12]}]
set_property IO_L7P_T1_D09_14 [get_ports {dac_data[13]}]
set_property IO_L7N_T1_D10_14 [get_ports {dac_clk}]

#Clock section
set_property IOSTANDARD LVCMOS33 [get_ports {input_clk}]

set_property IO_L8P_T1_D11_14 [get_ports {input_clk}]

#ADC section
set_property IOSTANDARD LVCMOS33 [get_ports {adc_clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_power_down}]

set_property IO_L8N_T1_D12_14 [get_ports {adc_clk}]
set_property IO_L9P_T1_DQS_14 [get_ports {adc_data[0]}]
set_property IO_L9N_T1_DQS_D13_14 [get_ports {adc_data[1]}]
set_property IO_L10P_T1_D14_14 [get_ports {adc_data[2]}]
set_property IO_L10N_T1_D15_14 [get_ports {adc_data[3]}]
set_property IO_L11P_T1_SRCC_14 [get_ports {adc_data[4]}]
set_property IO_L11N_T1_SRCC_14 [get_ports {adc_data[5]}]
set_property IO_L12P_T1_MRCC_14 [get_ports {adc_data[6]}]
set_property IO_L12N_T1_MRCC_14 [get_ports {adc_data[7]}]
set_property IO_L13P_T2_MRCC_14 [get_ports {adc_power_down}]



#set_property IO_L13N_T2_MRCC_14 [get_ports {kimenet_xxx}]
#set_property IO_L14P_T2_SRCC_14 [get_ports {kimenet_xxx}]
#set_property IO_L14N_T2_SRCC_14 [get_ports {kimenet_xxx}]
#set_property IO_L15P_T2_DQS_RDWR_B_14 [get_ports {kimenet_xxx}]
#set_property IO_L15N_T2_DQS_DOUT_CSO_B_14 [get_ports {kimenet_xxx}]
#set_property IO_L16P_T2_CSI_B_14 [get_ports {kimenet_xxx}]
#set_property IO_L16N_T2_D31_14 [get_ports {kimenet_xxx}]
#set_property IO_L17P_T2_D30_14 [get_ports {kimenet_xxx}]
#set_property IO_L17N_T2_D29_14 [get_ports {kimenet_xxx}]
#set_property IO_L18P_T2_D28_14 [get_ports {kimenet_xxx}]
#set_property IO_L18N_T2_D27_14 [get_ports {kimenet_xxx}]
#set_property IO_L19P_T3_D26_14 [get_ports {kimenet_xxx}]
#set_property IO_L19N_T3_D25_VREF_14 [get_ports {kimenet_xxx}]
#set_property IO_L20P_T3_D24_14 [get_ports {kimenet_xxx}]
#set_property IO_L20N_T3_D23_14 [get_ports {kimenet_xxx}]
#set_property IO_L21P_T3_DQS_14 [get_ports {kimenet_xxx}]
#set_property IO_L21N_T3_DQS_D22_14 [get_ports {kimenet_xxx}]
#set_property IO_L22P_T3_D21_14 [get_ports {kimenet_xxx}]
#set_property IO_L22N_T3_D20_14 [get_ports {kimenet_xxx}]
#set_property IO_L23P_T3_D19_14 [get_ports {kimenet_xxx}]
#set_property IO_L23N_T3_D18_14 [get_ports {kimenet_xxx}]
#set_property IO_L24P_T3_D17_14 [get_ports {kimenet_xxx}]
#set_property IO_L24N_T3_D16_14 [get_ports {kimenet_xxx}]
#set_property IO_25_14 [get_ports {kimenet_xxx}]
#set_property IO_0_34 [get_ports {kimenet_xxx}]
#set_property IO_L1P_T0_34 [get_ports {kimenet_xxx}]
#set_property IO_L1N_T0_34 [get_ports {kimenet_xxx}]
#set_property IO_L2P_T0_34 [get_ports {kimenet_xxx}]
#set_property IO_L2N_T0_34 [get_ports {kimenet_xxx}]
#set_property IO_L3P_T0_DQS_34 [get_ports {kimenet_xxx}]
#set_property IO_L3N_T0_DQS_34 [get_ports {kimenet_xxx}]
#set_property IO_L4P_T0_34 [get_ports {kimenet_xxx}]
#set_property IO_L4N_T0_34 [get_ports {kimenet_xxx}]
#set_property IO_L5P_T0_34 [get_ports {kimenet_xxx}]
#set_property IO_L5N_T0_34 [get_ports {kimenet_xxx}]
#set_property IO_L6P_T0_34 [get_ports {kimenet_xxx}]
#set_property IO_L6N_T0_VREF_34 [get_ports {kimenet_xxx}]
#set_property IO_L7P_T1_34 [get_ports {kimenet_xxx}]
#set_property IO_L7N_T1_34 [get_ports {kimenet_xxx}]
#set_property IO_L8P_T1_34 [get_ports {kimenet_xxx}]
#set_property IO_L8N_T1_34 [get_ports {kimenet_xxx}]
#set_property IO_L9P_T1_DQS_34 [get_ports {kimenet_xxx}]
#set_property IO_L9N_T1_DQS_34 [get_ports {kimenet_xxx}]
#set_property IO_L10P_T1_34 [get_ports {kimenet_xxx}]
#set_property IO_L10N_T1_34 [get_ports {kimenet_xxx}]
#set_property IO_L11P_T1_SRCC_34 [get_ports {kimenet_xxx}]
#set_property IO_L11N_T1_SRCC_34 [get_ports {kimenet_xxx}]
#set_property IO_L12P_T1_MRCC_34 [get_ports {kimenet_xxx}]
#set_property IO_L12N_T1_MRCC_34 [get_ports {kimenet_xxx}]
#set_property IO_L13P_T2_MRCC_34 [get_ports {kimenet_xxx}]
#set_property IO_L13N_T2_MRCC_34 [get_ports {kimenet_xxx}]
#set_property IO_L14P_T2_SRCC_34 [get_ports {kimenet_xxx}]
#set_property IO_L14N_T2_SRCC_34 [get_ports {kimenet_xxx}]
#set_property IO_L15P_T2_DQS_34 [get_ports {kimenet_xxx}]
#set_property IO_L15N_T2_DQS_34 [get_ports {kimenet_xxx}]
#set_property IO_L16P_T2_34 [get_ports {kimenet_xxx}]
#set_property IO_L16N_T2_34 [get_ports {kimenet_xxx}]
#set_property IO_L17P_T2_34 [get_ports {kimenet_xxx}]
#set_property IO_L17N_T2_34 [get_ports {kimenet_xxx}]
#set_property IO_L18P_T2_34 [get_ports {kimenet_xxx}]
#set_property IO_L18N_T2_34 [get_ports {kimenet_xxx}]
#set_property IO_L19P_T3_34 [get_ports {kimenet_xxx}]
#set_property IO_L19N_T3_VREF_34 [get_ports {kimenet_xxx}]
#set_property IO_L20P_T3_34 [get_ports {kimenet_xxx}]
#set_property IO_L20N_T3_34 [get_ports {kimenet_xxx}]
#set_property IO_L21P_T3_DQS_34 [get_ports {kimenet_xxx}]
#set_property IO_L21N_T3_DQS_34 [get_ports {kimenet_xxx}]
#set_property IO_L22P_T3_34 [get_ports {kimenet_xxx}]
#set_property IO_L22N_T3_34 [get_ports {kimenet_xxx}]
#set_property IO_L23P_T3_34 [get_ports {kimenet_xxx}]
#set_property IO_L23N_T3_34 [get_ports {kimenet_xxx}]
#set_property IO_L24P_T3_34 [get_ports {kimenet_xxx}]
#set_property IO_L24N_T3_34 [get_ports {kimenet_xxx}]
#set_property IO_25_34 [get_ports {kimenet_xxx}]