# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/workshop2/clocks.xdc

# XDC: imports/workshop2/ports.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_c_addsub_0_0/top_c_addsub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_c_addsub_0_0 || ORIG_REF_NAME==top_c_addsub_0_0} -quiet] -quiet

# IP: bd/top/ip/top_c_counter_binary_i_0/top_c_counter_binary_i_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_c_counter_binary_i_0 || ORIG_REF_NAME==top_c_counter_binary_i_0} -quiet] -quiet

# IP: bd/top/ip/top_c_counter_binary_q_0/top_c_counter_binary_q_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_c_counter_binary_q_0 || ORIG_REF_NAME==top_c_counter_binary_q_0} -quiet] -quiet

# IP: bd/top/ip/top_dds_config_gen_0_0/top_dds_config_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dds_config_gen_0_0 || ORIG_REF_NAME==top_dds_config_gen_0_0} -quiet] -quiet

# IP: bd/top/ip/top_cplx_sep_0_0/top_cplx_sep_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_cplx_sep_0_0 || ORIG_REF_NAME==top_cplx_sep_0_0} -quiet] -quiet

# IP: bd/top/ip/top_dds_compiler_0_0/top_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_dds_compiler_0_0 || ORIG_REF_NAME==top_dds_compiler_0_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_freq_0/top_xlconstant_freq_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_freq_0 || ORIG_REF_NAME==top_xlconstant_freq_0} -quiet] -quiet

# IP: bd/top/ip/top_xlconstant_offs_0/top_xlconstant_offs_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xlconstant_offs_0 || ORIG_REF_NAME==top_xlconstant_offs_0} -quiet] -quiet

# IP: bd/top/ip/top_mult_gen_i_0/top_mult_gen_i_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mult_gen_i_0 || ORIG_REF_NAME==top_mult_gen_i_0} -quiet] -quiet

# IP: bd/top/ip/top_mult_gen_q_0/top_mult_gen_q_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_mult_gen_q_0 || ORIG_REF_NAME==top_mult_gen_q_0} -quiet] -quiet

# XDC: bd/top/top_ooc.xdc
